### ISSUE TITLE
Can't compile example with calling self methods in generic class

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#69]
#### Reproduction:

```ts
export class Foo< T > { // Without tepmlate <T> compiles with success
      num1: int32;
      num2: int32;
 
     constructor() {
          this.num1 = 1;
          this.num2 = 2;
     }

      get length(): int32 {
            return this.num1;
      }
      operator [](index: int32): int32 {
            return this.num2 + index;
      }

      mainAccessTest(index: int32): int32 {
            return this[index] + this.length; // <-- assertion failed in this part
      }
}
```
#### Output:

```cmd
Error: Assertion failed
    at stdlib.assert (.../TurboScript/lib/tc.js:10:23)
    at Node.dotTarget .../TurboScript/lib/turbo.js:14275:21)
    at resolve (.../TurboScript/lib/turbo.js:12224:31)
    at resolveAsExpression (.../TurboScript/lib/turbo.js:11667:9)
    at resolve (.../TurboScript/lib/turbo.js:12271:13)
    at resolveAsExpression (.../TurboScript/lib/turbo.js:11667:9)
    at resolve (.../TurboScript/lib/turbo.js:12641:13)
    at resolveAsExpression (.../TurboScript/lib/turbo.js:11667:9)
    at resolve (.../TurboScript/lib/turbo.js:12407:13)
    at resolveChildren (.../TurboScript/lib/turbo.js:11651:13)
```

**Comment by nidin** [comment]
Could you please add it as a test case?

**Comment by MaxGraey** [comment]
sure!

**Comment by MaxGraey** [comment]
I added it to manual tests. After you resolve add to automatic test directory as well

**Comment by nidin** [comment]
You don't need to close the issue manually. Wafflebot close it automatically when the pull request merge 😎

**Comment by MaxGraey** [comment]
Sure, I forgot that we have bot for this routine)

**Comment by nidin** [comment]
☺️
